import 'dotenv/config';
import { ExpressServer } from './server/ExpressServer';
import { HttpServer } from './contracts/HttpServer';
import { UserExpressRouter } from './routes/UserExpressRouter';
import { UserService } from '@services/UserService';
import UserController from '@controllers/UserController';
import { JsonWebToken } from '@contracts/JsonWebToken';
import { JwtService } from '@services/JwtService';
import { UserRepository } from '@contracts/UserRepository';
import { MediaService } from '@contracts/MediaService';
import { CloudinaryService } from '@services/CloudinaryService';
import { MulterMiddleware } from '@middlewares/MulterMiddleware';
import { ExpressTokenMiddleware } from '@middlewares/ExpressTokenMiddleware';
import { PetService } from '@services/PetService';
import { PrismaUserRepository } from '@repositories/PrismaUserRepository';
import { PetRepository } from '@contracts/PetRepository';
import { PrismaPetRepository } from '@repositories/PrismaPetRepository';
import PetController from '@controllers/PetController';
import { PetExpressRouter } from '@routes/PetExpressRouter';
import { Prisma } from '@libs/prisma';

const httpServer: HttpServer = new ExpressServer();
const prisma = Prisma.getInstance();
const userRepository: UserRepository = new PrismaUserRepository(prisma);
const petRepository: PetRepository = new PrismaPetRepository(prisma);
const jwtService: JsonWebToken = new JwtService(process.env.JWT_SECRET || 'development_secret');
const mediaService: MediaService = new CloudinaryService();
const userService = new UserService(jwtService, userRepository, mediaService);
const petService = new PetService(petRepository, mediaService);
const userController = new UserController(userService);
const petController = new PetController(petService);
const multerMiddleware = new MulterMiddleware();
const expressTokenMiddleware = new ExpressTokenMiddleware(jwtService);
const userRouter = new UserExpressRouter(userController, multerMiddleware, expressTokenMiddleware);
const petRouter = new PetExpressRouter(petController, multerMiddleware, expressTokenMiddleware);
httpServer.routes('/pets', petRouter);
httpServer.routes('/users', userRouter);
httpServer.listen(3000, () => {
    console.log('Servidor rodando na porta 3000');
});
